### PR TITLE
Enhance underlying EMF meta-model and GUI to support SHACL shapes.

### PR DESCRIPTION
**Pull request by yashkhatri**
Added a new Shacl Specification Diagram. Enhanced the underlying meta-model and GUI.

Code verified for new models. Need to verify if the existing models are working fine.

### CODE REVIEW

**Comment by yashkhatri** [comment]
Updates on Comment by Jad:

**The EMF model**

> 1. OSLC Resource has a "describes" property pointing it to a vocabulary class. How does SHACL relate a shape to a vocab? Can we also model that?

_Was thinking to introduce pointing to vocabulary in later patches. Should I add "describes" in this patch only? And like OSLC shapes, Shacl Shapes describes itself?_

> Both OSLC and SHACL properties share the same list for Value/DataType. Is that desired? Is there a risk that the 2 standards differ in the list of supported types? In particular, does it make sense to talk about LocalResource in SHACL? (see later comment in the odesign file)

_Fixed! Created a new ShaclDataType Enum._

> The EMF-generated java files have a lot of white-space changes. I think you need to change the eclipse settings to use 4 spaces for a tab.

_Tried!_

**ToolChainModel.odesign**

> 1. DomainSpecs: the 2 right-clicking operations are not available in the Shacl Specs.


_Fixed!_

> 2. Property: The property label shows [min ... max]. I think this is quite verbose, plus unlike DomainSpecs. If we want to change this, we should do it consistently in both models. Let's discuss for a later patch.
> Note also that this info is NOT shown consistently when the property is listed under the shape! Depending on whether min and/or max are 0 and/or 1, "[]" is shown, or nothhing at all? Seems inconsistent.

_Shacl shapes have the concept of min and max which lacks in OSLC shapes. Not including these information in the label will lead to loss of this info. However, it is always present in property view. Need to decide on it._

> Do we need "Local Reference Properties" commands and operations? Does SHACL even have this notation of local shapes?

_No we don't. Discussed this with Jad. Removed!_

**Overall**

> 1. A ShaclSpecification diagram is rightly created when a new toolchain model is created. I think this is good. But until SHACL implementation is more stable, maybe we should NOT create this diagram, making it hidden unless people know about it. We add this behaviour once we are more confident.

_Agree! Removed the automatic initialisation._ 

> 2. I cannot allocate SHACL shapes to adaptors in the toolchain view.
> I don't think we need to fix it in this patch.
> Suggestion is to make this fix in the next patch.

_In the upcoming patch_

**Comment by jadelkhoury** [comment]
@berezovskyi Yes, we start simple. let's add complexity on a need-basis.
Main focus now is to have a structure that supports both Shapes, and we extend later.

**Comment by jadelkhoury** [comment]
> Updates on Comment by Jad:
> 
> **The EMF model**
> 
> > 1. OSLC Resource has a "describes" property pointing it to a vocabulary class. How does SHACL relate a shape to a vocab? Can we also model that?
> 
> _Was thinking to introduce pointing to vocabulary in later patches. Should I add "describes" in this patch only? And like OSLC shapes, Shacl Shapes describes itself?_

We can do in later patch. But I wonder what the SHACL specs calls this relationship. "describes" is the OSLC term. We should adopt the SHACL term for SHACL resources.
 
> > Both OSLC and SHACL properties share the same list for Value/DataType. Is that desired? Is there a risk that the 2 standards differ in the list of supported types? In particular, does it make sense to talk about LocalResource in SHACL? (see later comment in the odesign file)
> 
> _Fixed! Created a new ShaclDataType Enum._

OK!

> > The EMF-generated java files have a lot of white-space changes. I think you need to change the eclipse settings to use 4 spaces for a tab.
> 
> _Tried!_

No luck? if the change is to make all white-spaces more consistent (say, to follow Linux EOL, which I believe is what is desired), then let's include such changes.
@berezovskyi shall we adopt Linux-EOL for generated code?
 
> **ToolChainModel.odesign**
> 
> > 1. DomainSpecs: the 2 right-clicking operations are not available in the Shacl Specs.
> 
> 
> _Fixed!_

I did not see changes to odesign file in the latest commit. Are you sure?

> > 2. Property: The property label shows [min ... max]. I think this is quite verbose, plus unlike DomainSpecs. If we want to change this, we should do it consistently in both models. Let's discuss for a later patch.
> > Note also that this info is NOT shown consistently when the property is listed under the shape! Depending on whether min and/or max are 0 and/or 1, "[]" is shown, or nothhing at all? Seems inconsistent.
> 
> _Shacl shapes have the concept of min and max which lacks in OSLC shapes. Not including these information in the label will lead to loss of this info. However, it is always present in property view. Need to decide on it._

Let's not add it to the label. As you say, it is in the Property view. In future patch, we decide more consitently how to show cardinality for both OSLC and SHACL properies.

> > Do we need "Local Reference Properties" commands and operations? Does SHACL even have this notation of local shapes?
> 
> _No we don't. Discussed this with Jad. Removed!_

OK.

> **Overall**
> 
> > 1. A ShaclSpecification diagram is rightly created when a new toolchain model is created. I think this is good. But until SHACL implementation is more stable, maybe we should NOT create this diagram, making it hidden unless people know about it. We add this behaviour once we are more confident.
> 
> _Agree! Removed the automatic initialisation._ 
> 
> > 2. I cannot allocate SHACL shapes to adaptors in the toolchain view.
> > I don't think we need to fix it in this patch.
> > Suggestion is to make this fix in the next patch.
> 
> _In the upcoming patch_

```

**Comment by jadelkhoury** [comment]
@yashkhatri! is this ready for review again? 
I see there is only 1 commit now, so wonder happened to the previous incremental changes.

**Comment by yashkhatri** [comment]
@jadelkhoury There were white space changes that were committed along with the previous changes. To ignore those changes, I have to rebase this branch against the base branch - master, commit only non white space changes and push again. That's why we see only one fat commit now.

**Comment by berezovskyi** [comment]
Please merge master into your branch instead of rebasing, otherwise you’d need to force push.

–Andrew.
(sent from my phone)

**Comment by jadelkhoury** [comment]
Good for now so we can proceed with code generation. There might be some code improvements to make to reuse logic from the OSLC domain specs.

**Pull request merged**
