### PR TITLE
Introduce setting to stop generating from imported models.

### LINKED ISSUE #164: Lyo Designer unnecessarily generates classes for resources that are already generated from an external library
I have Lyo.Domains on my classpath as I am also extending the Architecture Management `Resource` in my Domain Model. The `Authentication Configuration` uses several resources such as `DctermsDomainConstants` which are provided by Lyo.Domains. Instead of using the instances that are provided by the classpath library, Lyo will instead regenerate a local copy of them:

image

This might be related to #120?

### PR DESCRIPTION
**Pull request by jadelkhoury**
resolves #164 or is it solves #164.
Introduce setting to stop generating from imported models.

### CODE REVIEW

**Comment by jadelkhoury** [comment]
image

What do you of this approach? A simple flag at the AdaptorInterface or Specification level.
This is flag is a bit different from all the other "do not generate" flags, because it does not work hierarchically.

**Comment by berezovskyi** [comment]
May be too late but: I think it is easier to mark DS on the other side as published or unpublished. For every DS that the generated code is published on Maven, we do not generate the code, for every unpublished - we do. This will allow to import both kinds of models.

**Comment by jadelkhoury** [comment]
There is already a "do not generate" flag on each DS (or the whole specs model) that instructs the generate not to generate.
So we now have control from both directions, to cover all sorts of scenarios.

**Comment by berezovskyi** [comment]
awesome

**Pull request merged**
