### PR TITLE
Add oslc-ui project

### PR DESCRIPTION
**Pull request by AndreyBespamyatnov**

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@berezovskyi @jamsden I will do a demo adpator that uses this new code for DUIs and UI previews.
In the meantime, it's worth discussing where we should host this code.

it doesn't fit under Lyodesigner. I suggested this pull request to @AndreyBespamyatnov so that we can get started.
Should we create a new repo under Lyo?

**Review by jamsden — COMMENTED** [review]
I can't tell what this code is doing without further discussion. I need to know the requirements, use cases, design principles, technical architecture, etc. in order to know how this might fit into Lyo overall, and how Lyo Designer generated code might leverage it as reusable code or as an exemplar for new templates.

**Comment by jadelkhoury** [comment]
Fair enough. I will fix a demo adaptor to illustrate.

**Comment by jadelkhoury** [comment]
@berezovskyi @jamsden 
So, the main idea here is to replace the jsp-pages for the DUI and UI-Preview. This project uses Angular instead.
And instead of generating specific jsp-pages for each class (that represent an OSLC resource type), the code works generically.

See the comments I placed under https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/56 that I hope explains what this implies. 

To see the results in action, you can see these 2 videos. The point of the 2 videos is to illustrate that one can configure what is to be shown in the search results, as well as in hte small and large previews.

* https://kth.box.com/s/zuhizzctn9vja19udpasszcbbx2u59kg 
* https://kth.box.com/s/9gvtqql6ixb94p4hptx8vapsceujh981

**Comment by jamsden** [comment]
Maybe we can schedule a demo? This is hard to visualize just from the code. 

Re: Angular, IBM has standardized on React and the Carbon components. Just an f.y.i.

**Comment by berezovskyi** [comment]
Sorry, missed this PR. Will try to check it over the weekend, too many things this week.

--  
Andrew

**Comment by jadelkhoury** [comment]
No probs @berezovskyi. 
A demo and discussion would be good. I see this as a starting point for something that eventually replaces all jsp pages (at least for DUIs and Previews). But most likely, it will take some time before we start generating code to fit it.

I am not familiar with neither Angular nor React. So, we need to also consider the maintainability aspect of this contribution.

**Comment by jadelkhoury** [comment]
If we agree to have this, let us start by creating the repo. We can then deal with your questions at the same time.

* jsonschema2pojo: @AndreyBespamyatnov Do we need this as part of the project? 

* PreviewFactory.java: This was manually created (by me). It is not compiled. It is indeed just to be copied together with the other java classes created by jsonschema2pojo. 
Besides that, I am not sure I got what you mean @berezovskyi

**Comment by berezovskyi** [comment]
@jadelkhoury preferred repo name?

**Comment by jadelkhoury** [comment]
tough question. 
lyo.oslc-ui: is good, but is all too encompassing. It would be good name, if we can use that same repo for many other such components. 

And how about "lyo.server-ui"?

**Comment by berezovskyi** [comment]
server-ui is a bit strange. server implies backend and UI in this case is a frontend 🤔 

otherwise we can just move this under `lyo.server` until we can decide

**Comment by jadelkhoury** [comment]
not lyo.server. That always confuses me. Most of the stuff in lyo is about server.

Let' go with lyo.oslc-ui

**Comment by berezovskyi** [comment]
I actually thought to move some stuff from core to server but always found smth better to do.

For tracking: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567853

**Comment by jadelkhoury** [comment]
move some stuff from core to server: Not sure if it makes sense. oslc-client depends on a lot of stuff from core. It will not make sense if client becomes dependent on "server". Instead, I'd rather we move stuff from server to core.

**Comment by jadelkhoury** [comment]
https://github.com/eclipse/lyo.oslc-ui is now available.
I'll push this code there, and we take it from there.

**Comment by jadelkhoury** [comment]
@berezovskyi @AndreyBespamyatnov 
I have now clone the code to https://github.com/eclipse/lyo.oslc-ui
I can't do a pull-request, because there is just 1 branch there (oslc-ui). 
I am sure there is a more correct way but now it is done :-)

Changes I made:
* I did not commit the jsonschema2pojo library. Instead, I added instructions in the readme file on how to donwload the files instead.

**Comment by berezovskyi** [comment]
Let's discuss first and make changes then.

First, I will merge this PR and delete the files from here to create a legal record of Andrei's PR as a commit, otherwise it looks like you are pushing his code without PR. 

Second, I want the repo to work, so it's bad to have blobs but better to have blobs rather than to have a repo that does not build.

**Comment by jadelkhoury** [comment]
ok. You ignore my push then. But maybe you can then just update the start of the readme.md file with teh following? Just so we don'thave to work it out again. 

## How to use 
After cloning this git repository
1. download and install jsonschema2pojo
    1. Download the 1.0.2 release (jsonschema2pojo-1.0.2.zip) from https://github.com/joelittlejohn/jsonschema2pojo/releases
    1. Unzip into the folder `oslc-ui\libs\`. (that is, under the path `oslc-ui\libs\jsonschema2pojo-1.0.2`, there should be `bin` & `lib` folders)
1. Go the root folder of the repo.
1. run `npm run build:elements-prod`...

**Comment by berezovskyi** [comment]
Hi, I just reviewed this PR locally and applied it on one of the OSLC RefImpl adaptors. Seems to work great except for matching the iframe size but I think we can file it as a bug once we merge this in and then move it to the new repo. Please note I had to remove windows-specific bits in the NPM scripts and you might have to use Git Bash or WSL2 to run npm commands on this repo in the future under Windows.

@AndreyBespamyatnov great work and thank you!

@AndreyBespamyatnov @jadelkhoury if you don't have objections to my last commit, I will proceed with the merge and repo migration.

**Review by berezovskyi — APPROVED** [review]

**Comment by jadelkhoury** [comment]
Go ahead and merge so that we can take some next steps. Thanks andrii

**Comment by jadelkhoury** [comment]
@berezovskyi Just to be sure, are you planning to do the next steps, or should i?

**Comment by berezovskyi** [comment]
Yes, I will. Most likely when our current work is wrapped up this week.

**Comment by berezovskyi** [comment]
Done, please head over to https://github.com/eclipse/lyo.oslc-ui for future work.

Tracking https://bugs.eclipse.org/bugs/show_bug.cgi?id=568317 to undo Jad's push because I lack admin rights on the repo.

**Comment by jadelkhoury** [comment]
@berezovskyi The Bugzilla issues seems to be resolved. Anything more you need to repair, before we are all set on that repo?

**Comment by berezovskyi** [comment]
I think we are all set!

**Pull request merged**
