### PR TITLE
pom configuration for jar signing

### LINKED ISSUE #135: sign all plugins and products
it would be good if we can get all our plugins (and new product) signed, so one avoids the warnings when one installs/updates.

Is it as simple as presented here?
https://wiki.eclipse.org/IT_Infrastructure_Doc#Sign_my_Jar.2Fplugins.2FWindows_exe.2FmacOS_App_files.3F

### PR DESCRIPTION
**Pull request by jadelkhoury**
resolves #135.

Just a first setup of the pom file. 

@berezovskyi ! Is there a way I can trigger jenkins on this branch for testing purposes? we'd need to do this before we know it works, and hence pushed to master.

### CODE REVIEW

**Comment by jadelkhoury** [comment]
Yes! I go the plugins signed. Not sure the pom is very clean, but latest commit builds on Jenkins, and signs the jars properly. Can be tested using the update site:
tools-updatesite - http://download.eclipse.org/lyo/p2/sign

**Comment by berezovskyi** [comment]
Awesome!

**Comment by berezovskyi** [comment]
See https://ci.eclipse.org/lyo/view/1Enabled/job/lyo-core-pr/configure for an example build config to run on PR branches. Note how the branch is specified and the pull request builder is used as a trigger.

**Comment by jadelkhoury** [comment]
Finally some instructions on how to use so I don't have to guess, nor copy from other projects.
https://git.eclipse.org/c/cbi/org.eclipse.cbi.git/tree/maven-plugins/README.md

**Comment by jadelkhoury** [comment]
and now I have the Windows exe signed. No warnings when file is downloaded.
@berezovskyi it would be great if you can test on a mac?
https://download.eclipse.org/lyo/product/binaries/edge/  ; File lyo-designer-macosx.cocoa.x86_64.zip

**Comment by jadelkhoury** [comment]
@berezovskyi I know you have done it in other scenarios, but it would be great if you have tips on how I can translate "SNAPSHOT" with a real snapshot number/date. Currently, the files are called 
lyo-designer-4.0.0-SNAPSHOT-linux.gtk.x86.zip.

**Comment by berezovskyi** [comment]
Try mvn clean tycho-versions:set-version -DnewVersion=2.4.0 -DforceStdout -B

Some places may require manual changes after that

--
Cheers,
Andrew

On 2020-01-19 , at 13:02, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


@berezovskyi<https://github.com/berezovskyi> I know you have done it in other scenarios, but it would be great if you have tips on how I can translate "SNAPSHOT" with a real snapshot number/date. Currently, the files are called
lyo-designer-4.0.0-SNAPSHOT-linux.gtk.x86.zip.

**Pull request merged**
