### PR TITLE
[WIP] enabling download stats for plugins, and RPC.

### PR DESCRIPTION
**Pull request by jadelkhoury**
enabling download stats for plugins, and RPC.

I will need to see if we do actually get stats, before we can merge to master,

### CODE REVIEW

**Review by berezovskyi — APPROVED** [review]

**Comment by jadelkhoury** [comment]
I downloaded plugins and features from https://download.eclipse.org/lyo/p2/superedge/
I also downloaded products, plugins and features from: https://download.eclipse.org/lyo/product/p2/superedge/
But still not much in the stats https://dev.eclipse.org/committers/committertools/stats.php

**Comment by berezovskyi** [comment]
We might have to wait 24h to see anything

**Comment by berezovskyi** [comment]
image

in general, the thing does seem to work, let's check tomorrow evening

**Comment by jadelkhoury** [comment]
The stats work but the question if my setup was correct. But we can now already see results (2 downloads).
Next is to check if this is also comming from the RCP. I Will download 1 RCP and see if it registers.

My suspicion: downloading the zip file doesn’t register in the log. But when the plugins are updated, it is logged.

**Comment by berezovskyi** [comment]
For the future the stats query: `/stats/org.eclipse.lyo.%`

For the product, I think we shall use the link https://www.eclipse.org/downloads/download.php?file=/lyo/product/binaries/stable/lyo-designer-linux.gtk.x86.zip for it to be logged

**Comment by berezovskyi** [comment]
I also recall seeing links of form https://download.eclipse.org/lyo/product/binaries/stable/lyo-designer-win32.win32.x86.zip?d=1 but not sure if they are counted as well.

**Comment by berezovskyi** [comment]
I think the mirror trick worked and the d=1 did not:

image

**Comment by jadelkhoury** [comment]
not sure what the mirror trick is. But this seems to be working.

**Comment by berezovskyi** [comment]
https://www.eclipse.org/downloads/download.php?file=/lyo/product/binaries/stable/lyo-designer-linux.gtk.x86.zip

**Pull request merged**
