### PR TITLE
Support for LyoStore

### PR DESCRIPTION
**Pull request by jadelkhoury**
Model and generation support for LyoStore.
For a given adaptor, OSLC and Web services can be mapped to a triple store. This way, C.R.U.D, as well as query and DUI capabilities can be implemented to access data from the store.

By default only GET, Query and SelectionDUI are mapped. But designer can choose to map the other operations as well.

See following for the resulting code.
https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/53

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@berezovskyi  @jamsden ! Any feedback on the resulting java code is much appreciated.

I have not thoroughly tested the code. But it is working. I would like to get feedback on the Java code, before I finalize.

**Comment by berezovskyi** [comment]
Thanks Jad! I left a few comments on the non-PR PR here https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/53/files

In general, I would suggest to contribute the StorePool to the lyo-store and not to generate it.

Your code is almost thread-safe, you need to check the bounds once again in the critical section.

I think you can get away with throwing exceptions in the Manager class but I am not sure whether one in the Pool class is good. Though I think we really should make sure user client errors result in 4xx errors unless it's something unexpected.

I think using https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html#take() would be better. The requests will start taking longer once the server has more than 500 requests per seconds according to your defaults.

**Comment by jadelkhoury** [comment]
Thanks Andrii.

Agree that StorePool should endup in the library. Shall fix.

I want to refactor this Manager class soon. So as long as  I don't do irreparable damage, I am happy to fix things all at once more consistently.

you might need to clarify to me what you want to do with the Queue interface.

**Comment by jadelkhoury** [comment]
This assumes the storePool class is part of the LyoStore
https://github.com/eclipse/lyo.store/pull/60

**Comment by jadelkhoury** [comment]
Closing this PR, since I started a new PR instead https://github.com/eclipse/lyo.designer/pull/171 (Don't ask why)

**Pull request closed without merging**
