### PR TITLE
Specify keys for EAttributes within their containing EClass

### PR DESCRIPTION
**Pull request by jadelkhoury**
Specify keys for EAttributes within their containing EClass, if they form a set.

This allows for more robust ids when such EAttributes are references
from other parts of hte model (Specifically when references are across
different EMF model files).

For example on how the model will look like, see the file changes on the pull-request on lyo-adaptor-sample-modelling https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/28/files

### CODE REVIEW

**Comment by jadelkhoury** [comment]
Some more information ....

References to model elements (Such as a resourceProperty) that reside in another file (for example, referring to rdfs:label from the model on https://github.com/eclipse/lyo.domains) might get corrupted.
Why? 

The resourceProperty reference is saved as 
 href="../org.eclipse.lyo.tools.domainmodels/oslcDomainSpecifications.xml#//@domainSpecifications**.0**/@resourceProperties**.8**"/>

Notice the index numbers that form the key. This means that a reordering of resourcesProperties within domainSpecifications**.0* causes the reference to point to wrong item.

Solution: use the following reference
href="../org.eclipse.lyo.tools.domainmodels/oslcDomainSpecifications.xml#//@domainSpecifications**[name='Dublin%20Core']**/@resourceProperties**[name='title']**"

The disadvantageous is of course that a change of the name (or whatever we choose as key) will cause the reference to get corrupted.

**NOTE**: This issue is ONLY relevant with external referencing. References within the 1 file are handled very ok by EMF.

**Comment by berezovskyi** [comment]
1) what is the impact on compat?
2) can we use some permanent EMF ident instead of a title?

--
/Andrew
(from phone)



On Thu, Apr 4, 2019 at 11:09 PM +0200, "Jad El-khoury" <notifications@github.com<mailto:notifications@github.com>> wrote:


Some more information ....

References to model elements (Such as a resourceProperty) that reside in another file (for example, referring to rdfs:label from the model on https://github.com/eclipse/lyo.domains) might get corrupted.
Why?

The resourceProperty reference is saved as
href="../org.eclipse.lyo.tools.domainmodels/oslcDomainSpecifications.xml#//@domainSpecifications**.0**/@resourceProperties**.8**"/>

Notice the index numbers that form the key. This means that a reordering of resourcesProperties within domainSpecifications**.0* causes the reference to point to wrong item.

Solution: use the following reference
href="../org.eclipse.lyo.tools.domainmodels/oslcDomainSpecifications.xml#//@domainSpecifications**[name='Dublin%20Core']/@resourceProperties[name='title']**"

The disadvantageous is of course that a change of the name (or whatever we choose as key) will cause the reference to get corrupted.

NOTE: This issue is ONLY relevant with external referencing. References within the 1 file are handled very ok by EMF.

**Comment by jadelkhoury** [comment]
> 1) what is the impact on compat? 

As far as I could see from my tests, old files open fine with the new model.  I thought I would have to do some sort of transformation between the changing meta-model, but that was handled fine by EMF.
See https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/28#issuecomment-480145047 

I see one issue: What to do with the models under https://github.com/eclipse/lyo.domains? If we update them, then I am pretty sure (I did not test) old models might no longer be able to reference to them.

> 2) can we use some permanent EMF ident instead of a title?

Nothing I am aware of. 
I wondered why EMF would even consider adopting the default of a simple integer increment otherwise.
We can probably define our own "hidden" ids, which (1) we need to automatically populate (2) somehow keep hidden from user changes.

**Comment by berezovskyi** [comment]
I would strongly suggest adding an 'id' field and initialising it with [`EcoreUtil.generateUUID()`](http://blog.vogella.com/2010/03/11/emf-unique-ids/). Otherwise we are just risking exchanging one headache for another.

**Comment by jadelkhoury** [comment]
I did not want to introduce this logic through Sirius, since one can potentially create the toolchain model in different ways (for example, programatically), hence any code at the Sirius level is bypassed. 

I tried to work out how to do it through the ecore model, but never occured to me that actually generate JAVA code from the Ecore model!

For example, https://stackoverflow.com/questions/6474895/what-is-the-best-way-to-auto-generate-values-for-features-when-an-eobject-is-cre

**Comment by berezovskyi** [comment]
Yep, that looks good! Do you want me to help with this somehow?

**Comment by jadelkhoury** [comment]
> Yep, that looks good! Do you want me to help with this somehow?

Your reviews (and pickiness) are good help

**Pull request merged**
