### PR TITLE
Add JSON-LD to the Consumes/Produces annotations

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by jadelkhoury** [comment]
I suggest we wait until after 2.4.0 release.

**Comment by berezovskyi** [comment]
Ok

--
/Andrew

On 25 Nov 2018, at 08:06, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


I suggest we wait until after 2.4.0 release.

**Comment by jadelkhoury** [comment]
+1 looks good to me. Thanks for the refactoring.

Is it tested though? (that is: Genereate code, plus test that requests for json-ld resources work)

**Comment by berezovskyi** [comment]
Yes, it was. See https://github.com/OSLC/lyo-adaptor-sample-modelling/pull/20. I checked with a wide variety of Accept headers but on a limited set of URLs; I assumed the refactoring with a query would make the behaviour uniform everywhere.

**Comment by jadelkhoury** [comment]
Go for it then. I recall we said that the contributor does the merge.

**Pull request merged**
