### PR TITLE
Refactor the code under the Domain Specification Diagram

### PR DESCRIPTION
**Pull request by jadelkhoury**
refactor the code under the Domain Specification Diagram, in order to
make it easier to reuse the model when defining the SHACL Diagram.

### CODE REVIEW

**Comment by jadelkhoury** [comment]
This is mainly for @yashkhatri to review.
Only changes to the representation of graphical entities are affected. Code relating to Operations is not changed. Code relating to the underlying model is not changed.

**Comment by jadelkhoury** [comment]
@yashkhatri I believe I identified all the hard-coded logic in the odesign file, which are now placed in the provided mtl file. If you find more, feel free to migrate.

**Comment by jadelkhoury** [comment]
I forgot to only commit non-whitespace changes to the odesign file. Please wait with review until I send a new patch.

**Comment by yashkhatri** [comment]
@jadelkhoury I will review and verify it soon. Have you already verified it?

**Comment by jadelkhoury** [comment]
I verified but I need to make a new commit without all the white-space changes

**Comment by berezovskyi** [comment]
BTW, you can hide whitespace changes from the diff.

–Andrew.
(sent from my phone)

**Comment by jadelkhoury** [comment]
From the diff yes, but they are still committed as changes. I want to remove the change from the commit.

**Comment by jadelkhoury** [comment]
Replacing this request with the cleaner one under https://github.com/eclipse/lyo.designer/pull/6

**Pull request closed without merging**
