### PR TITLE
Update for hte latest changes of lyo.client.

### PR DESCRIPTION
**Pull request by jadelkhoury**
@berezovskyi Do I have to change ALL versions in all pom files to 4.0.0-SNAPSHOT again?

### CODE REVIEW

**Comment by berezovskyi** [comment]
yes, and it would be best if you do it separately as a direct commit to master

**Comment by berezovskyi** [comment]
image

I did it right away in core, for example

**Review by berezovskyi — APPROVED** [review]
Please make sure to push this after you switch to 4.0.0-SNAPSHOT

**Comment by jadelkhoury** [comment]
I'm proud of me. I think I did it right.

**Comment by berezovskyi** [comment]
Yes, you did 💪 👌

**Pull request merged**
