### PR TITLE
closes #81 - Add a LyoDesigner version to the Application class

### LINKED ISSUE #81: Add a version & timestamp to the Application class or index.jsp
It would be good to have a comment, log message, or a notice in the JSP page with the LyoD version and time of generation, e.g.

```java
/**
 * Generated by Lyo Designer 4.0.0.201904250441 at 2019-05-09T13:30:29Z
 */
public class Application extends javax.ws.rs.core.Application {
...
}
```

### PR DESCRIPTION
**Pull request by jadelkhoury**
closes #81 - Add a LyoDesigner version to the Application class

### CODE REVIEW

**Comment by jadelkhoury** [comment]
Pull request is NOT ready to merge.

@berezovskyi !
The java class is in place, but I hope you can work out best way to extract hte bundle version.

It would also be nice if the version is in the footer/header of the html pages. You might know how to insert that neatly too.

**Comment by berezovskyi** [comment]
@jadelkhoury just implemented the method, please test.

**Comment by jadelkhoury** [comment]
tested. produces the text "Generated by Lyo Designer 4.0.0.qualifier".

**Comment by berezovskyi** [comment]
that's from the source. from p2 it should be Generated by Lyo Designer 4.0.0.201905222333 or something like that. Let's see after I fix the build

**Comment by jadelkhoury** [comment]
Sure. but that would be hard to test. So, let's hope it will work. Once we download the latest update, I can test again. (I guess that's what you meant too).

**Pull request merged**
