### PR TITLE
closes #30: SP URI contructors are private

### LINKED ISSUE #30: SP URI contructors are private
Methods like

    xyz.servlet.ServiceProviderCatalogSingleton#constructXyzServiceProviderURI

are private. I need access to this method to register and unregister SPs on-the-fly.

### LINKED ISSUE #36: Extra semicolon inserted in the SP Info class if the instance id was customised
image

the corresponding instance ID is `{twinKind}/{twinId}`

### PR DESCRIPTION
**Pull request by jadelkhoury**
closes #30: SP URI contructors are private

Also closes #36: Extra semicolon inserted in the SP Info class if the
instance id was customised

Providing a public method that can be used to create SP instances based
on SPInfo instances. This method can be dynically called to update the
set of provided SPs.

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@berezovskyi will this do?

**Comment by berezovskyi** [comment]
great, thank you! let me generate and test it.

**Comment by berezovskyi** [comment]
Getting 32 warnings:

```
org.eclipse.acceleo.engine.AcceleoEvaluationException: Invalid loop iteration at line 431 in Module generateResource for block for (unresolved query invocation : null()). Last recorded value of self was adaptorinterface.impl.ResourcePropertyImpl@3d98f7fc (title: null, name: deregister, occurs: exactlyOne, readOnly: false, valueType: Boolean, representation: n_a, description: null, allowedValue: [], isMemberProperty: n_a). Problem found while generating the file '/Users/andrew/kth/scott/scott/lyo-services/model-sandbox/domain-pddl/src/main/java/eu/scott/warehouse/domains/twins/DeviceRegistrationMessage.java'.
	at generateResource.generateAttributeToHtmlMethods(Resource,AdaptorInterface)(generateResource.mtl:431)
	at generateResource.generateAttributeToHtmlMethods(Resource,AdaptorInterface)(generateResource.mtl:428)
	at generateResource.generateAttributeToHtmlMethods(Resource,AdaptorInterface)(generateResource.mtl:427)
	at generateResource.generateResource(Resource,AdaptorInterface,String,String)(generateResource.mtl:0)
	at generateResource.generateResource(Resource,AdaptorInterface,String,String)(generateResource.mtl:540)
	at generateResource.generateResource(Resource,AdaptorInterface,String,String)(generateResource.mtl:539)
	at generate.generateForRelevantResources(AdaptorInterface)(generate.mtl:0)
	at generate.generateForRelevantResources(AdaptorInterface)(generate.mtl:108)
	at generate.generateForRelevantResources(AdaptorInterface)(generate.mtl:107)
	at generate.generate(AdaptorInterface)(generate.mtl:0)
	at generate.generate(AdaptorInterface)(generate.mtl:175)
```

**Comment by berezovskyi** [comment]
And this:

```
org.eclipse.acceleo.engine.AcceleoEvaluationException: Unresolved compilation error, expression was null.
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1895)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoQueryInvocation(AcceleoEvaluationVisitor.java:880)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1951)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoForBlock(AcceleoEvaluationVisitor.java:448)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1922)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoForBlock(AcceleoEvaluationVisitor.java:537)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1922)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoTemplate(AcceleoEvaluationVisitor.java:922)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1906)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoTemplateInvocation(AcceleoEvaluationVisitor.java:973)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1945)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoFileBlock(AcceleoEvaluationVisitor.java:431)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1935)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoTemplate(AcceleoEvaluationVisitor.java:922)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1906)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoTemplateInvocation(AcceleoEvaluationVisitor.java:973)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1945)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoForBlock(AcceleoEvaluationVisitor.java:537)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1922)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoTemplate(AcceleoEvaluationVisitor.java:922)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1906)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoTemplateInvocation(AcceleoEvaluationVisitor.java:973)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1945)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitAcceleoTemplate(AcceleoEvaluationVisitor.java:922)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.switchExpression(AcceleoEvaluationVisitor.java:1906)
	at org.eclipse.acceleo.engine.internal.evaluation.AcceleoEvaluationVisitor.visitExpression(AcceleoEvaluationVisitor.java:1049)
	at org.eclipse.ocl.internal.evaluation.QueryImpl.evaluate(QueryImpl.java:146)
	at org.eclipse.ocl.ecore.QueryImpl.evaluate(QueryImpl.java:56)
	at org.eclipse.acceleo.engine.generation.AcceleoEngine.doEvaluate(AcceleoEngine.java:365)
	at org.eclipse.acceleo.engine.generation.AcceleoEngine.evaluate(AcceleoEngine.java:142)
	at org.eclipse.acceleo.engine.service.AcceleoService.doGenerateTemplate(AcceleoService.java:984)
	at org.eclipse.acceleo.engine.service.AcceleoService.doGenerate(AcceleoService.java:641)
	at org.eclipse.acceleo.engine.service.AbstractAcceleoGenerator.generate(AbstractAcceleoGenerator.java:209)
	at org.eclipse.acceleo.engine.service.AbstractAcceleoGenerator.generate(AbstractAcceleoGenerator.java:172)
	at org.eclipse.acceleo.engine.service.AbstractAcceleoGenerator.doGenerate(AbstractAcceleoGenerator.java:159)
	at org.eclipse.lyo.oslc4j.codegenerator.main.Generate.doGenerate(Generate.java:202)
	at org.eclipse.lyo.tools.codegenerator.ui.common.GenerateAll$1.run(GenerateAll.java:126)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

and 

```
org.eclipse.acceleo.engine.AcceleoEvaluationException: Invalid loop iteration at line 222 in Module generateResource for block for (unresolved query invocation : null()). Last recorded value of self was adaptorinterface.impl.ResourceImpl@4a6d1ccd (name: Action). Problem found while generating the file '/Users/andrew/kth/scott/scott/lyo-services/model-sandbox/domain-pddl/src/main/java/eu/scott/warehouse/domains/pddl/Action.java'.
	at generateResource.generateConstructors(Resource,AdaptorInterface)(generateResource.mtl:222)
	at generateResource.generateConstructors(Resource,AdaptorInterface)(generateResource.mtl:203)
	at generateResource.generateResource(Resource,AdaptorInterface,String,String)(generateResource.mtl:0)
	at generateResource.generateResource(Resource,AdaptorInterface,String,String)(generateResource.mtl:540)
	at generateResource.generateResource(Resource,AdaptorInterface,String,String)(generateResource.mtl:539)
	at generate.generateForRelevantResources(AdaptorInterface)(generate.mtl:0)
	at generate.generateForRelevantResources(AdaptorInterface)(generate.mtl:108)
	at generate.generateForRelevantResources(AdaptorInterface)(generate.mtl:107)
	at generate.generate(AdaptorInterface)(generate.mtl:0)
	at generate.generate(AdaptorInterface)(generate.mtl:175)
```

and 

```
org.eclipse.acceleo.engine.AcceleoEvaluationException: Undefined condition of "If" at line 161 in Module generate for block if (unresolved query invocation : null()->isEmpty().not()). Last recorded value of self was adaptorinterface.impl.ResourceImpl@4933952d (name: DeviceRegistrationMessage).
	at generate.generateForServiceProviders(AdaptorInterface)(generate.mtl:161)
	at generate.generateForServiceProviders(AdaptorInterface)(generate.mtl:160)
	at generate.generateForServiceProviders(AdaptorInterface)(generate.mtl:114)
	at generate.generate(AdaptorInterface)(generate.mtl:0)
	at generate.generate(AdaptorInterface)(generate.mtl:178)
	at generate.generate(AdaptorInterface)(generate.mtl:175)
```

**Comment by berezovskyi** [comment]
So, I have cleaned as much as I could and restarted my "inner" Eclipse and got this when I clicked on an Adaptor in the Toolchain diag before I even got to right-click it and generate any code:

```
Compilation error for expression [self.oclIsTypeOf(AdaptorInterface)/] : Unrecognized variable: (AdaptorInterface)
```

**Comment by berezovskyi** [comment]
I am also missing the following method:

```
    public static boolean containsTwinsServiceProvider(String kind, String id) {
        final String serviceProviderIdentifier = twinsServiceProviderIdentifier(kind, id);
        return serviceProviders.containsKey(serviceProviderIdentifier);
    }
```

Both the map field and the identifier methods are private and I don't want to iterate over an array every time. But we can keep it as a separate patch. Together with the code that throws an exception when an SP is overwritten:

```
if (serviceProviders.containsKey(identifier)) {
            throw new IllegalArgumentException(
                String.format("The SP '%s' was already registered", identifier));
        }
```

**Comment by berezovskyi** [comment]
Here is the commit with me regenerating the code: https://github.com/EricssonResearch/scott-eu/commit/13f632b72a82d5392a7a4ae40d420f20955b5734 (has some manual "fixes" still)

**Comment by jadelkhoury** [comment]
Can we try to share a screen today to 
1. Work out your Acceleo warnings 
2. Work out what more changes are needed

**Comment by berezovskyi** [comment]
Those 32 warnings are gone and the code generation finishes w/o any warnings. Let's talk later today.

**Comment by jadelkhoury** [comment]
I suspect you did not follow the obsure Eclipse ritual of cleaning/recleaning/compiling/building/unbuilding of Accelo projects (with certain pages open in the Editor) before starting the new Eclipse instance.

Let's speak later then.

**Comment by berezovskyi** [comment]
🙈

**Comment by jadelkhoury** [comment]
@berezovskyi please see newly added method, plus the check you wanted.

**Pull request merged**
